### Get all contacts
GET http://localhost:3000/contacts
Content-Type: application/json

### Get single contact by ID
GET http://localhost:3000/contacts/1
Content-Type: application/json

### Create new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "name": "Richard LoRicco"
}

### Update contact
PUT http://localhost:3000/contacts/1
Content-Type: application/json

{
    "name": "Jane Doe"
}

### Delete contact
DELETE http://localhost:3000/contacts/1
Content-Type: application/json

### Reset database
POST http://localhost:3000/reset
Content-Type: application/json